\" Manpage for immortal.
.\" Contact nbari@tequila.io to correct errors or typos or use https://github.com/immortal/immortal/issues
.TH man 8 "19 Mar 2017" "1.0" "immortalctl man page"
.SH NAME
immortalctl \- control services started by immortal(8)
.SH SYNOPSIS
immortalctl [options] [-12achikinouqstvw] service
.SH DESCRIPTION
.SH OPTIONS
.SH ENVIRONMENT
.TP
.B IMMORTAL_SDIR
This environment variable allows to override the default supervise directory /var/run/immortal, used also by immortal(8) and immortaldir(8)

.SH EXAMPLES

.SH SEE ALSO
immortal(8), immortaldir(8)
.SH BUGS
https://github.com/immortal/immortal/issues
.SH AUTHOR
.PP
Nicolas Embriz <nbari@tequila.io>
.br
For more information, see the immortal homepage at
.br
https://immortal.run
