[workspace]
resolver = "3"
members = [
    "crates/immortal-core",
    "crates/immortal",
    "crates/immortalctl",
    "crates/immortaldir",
    "crates/immortallog",
]

[workspace.package]
version = "0.1.0"
authors = ["Nicolas Embriz <nbari@tequila.io>"]
edition = "2024"
rust-version = "1.97"
license = "BSD-3-Clause"
repository = "https://github.com/immortal/immortal"
homepage = "https://immortal.run"
publish = false

[workspace.dependencies]
built = { version = "0.8.1", features = ["git2"] }
clap = { version = "4.6", features = ["env"] }
fork = "=0.9.1"
immortal-core = { path = "crates/immortal-core" }
libc = "0.2"
nix = { version = "0.31.3", features = ["user"] }
notify = "8.2"
serde = { version = "1", features = ["derive"] }
serde-saphyr = "0.0.29"
serde_json = "1.0.150"
tokio = { version = "1.52", features = ["io-util", "macros", "net", "rt", "signal", "sync", "time"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[workspace.lints.rust]
warnings = "deny"
unsafe_code = "forbid"

[workspace.lints.clippy]
nursery = { level = "allow", priority = -1 }
pedantic = "deny"
all = "deny"
correctness = "deny"
suspicious = "deny"
perf = "deny"
complexity = "deny"
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
indexing_slicing = "deny"
await_holding_lock = "deny"
needless_borrow = "deny"
needless_collect = "deny"
large_stack_arrays = "deny"

[profile.release]
lto = "fat"
codegen-units = 1
strip = "symbols"
