[package]
name = "immortal-fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
immortal-core = { path = "../crates/immortal-core" }

[[bin]]
name = "config"
path = "fuzz_targets/config.rs"
test = false
doc = false
bench = false

[[bin]]
name = "control"
path = "fuzz_targets/control.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
